# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: cimg/openjdk:8.0.345
    steps:
      - checkout

      - run: mvn -B clean install